name: dice_poker
description: Dice Poker

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  equatable:
  bloc: ^3.0.0
  flutter_bloc: ^3.2.0
  auto_size_text:


dev_dependencies:
  flutter_test:
    sdk: flutter

# The following section is specific to Flutter.
flutter:

  uses-material-design: true

  assets:
  - assets/


  fonts:
     - family: Roboto
       fonts:
         - asset: assets/fonts/Roboto-Regular.ttf
         - asset: assets/fonts/Roboto-Bold.ttf
           weight: 700
         - asset: assets/fonts/Roboto-Italic.ttf
           style: italic

